section yachts without path to img
ratkus-dev/project-DevStudents pull request #10
Opened 2024-08-08 09:16 UTC by olexiy-kireyko

2024-08-08 10:25 UTC, ratkus-dev requested changes

2024-08-08 10:25 UTC, ratkus-dev commented on src/partials/yachts.html
> +    <button class="btn secondary-btn"><a href="#rent">Yacht rental</a></button>
в тег button мы ссылку не вкладываем, классы btn, secondary-btn должны быть на самой ссылке

2024-08-08 10:25 UTC, ratkus-dev commented on src/css/sections/yachts.css
> +.yachts .container {
я бы не добавлял стили на container лучше в него вложить div например yacht-content и эти стили повесить на него. Это не критично но лучше сделать так

2024-08-08 10:25 UTC, ratkus-dev commented on src/css/sections/yachts.css
> +    max-height: 19px;
высоту лучше убрать

2024-08-08 10:25 UTC, ratkus-dev commented on src/css/sections/yachts.css
> +.yachts-list-item {
твои карточки в итоге получаются разной ширины а в макете не так

2024-08-08 10:25 UTC, ratkus-dev commented on src/css/sections/yachts.css
> +  box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.25);
тени на картинке в макете нет

2024-08-08 10:25 UTC, ratkus-dev commented on src/css/sections/yachts.css
> +.yachts-card-line {
эту линию лучше реализовать как border-top на блоке который содержит параметры яхты

2024-08-08 10:25 UTC, ratkus-dev commented on src/css/sections/yachts.css
> +.yachts-card-testimonial {
пустой селектор

2024-08-08 10:25 UTC, ratkus-dev commented on src/css/sections/yachts.css
> +  opacity: 0.4;
opacity лечше сделать через алфа канал цвета текста

2024-08-08 10:25 UTC, ratkus-dev commented on src/css/sections/yachts.css
> +.yachts-card-value {
пустой селектор

2024-08-08 10:25 UTC, ratkus-dev commented on src/css/sections/yachts.css
> +  border-radius: 24%;
тут должно быть 24px

2024-08-08 10:37 UTC, olexiy-kireyko commented on src/partials/yachts.html
> +    <button class="btn secondary-btn"><a href="#rent">Yacht rental</a></button>
+

2024-08-08 10:40 UTC, olexiy-kireyko commented on src/css/sections/yachts.css
> +.yachts .container {
+

2024-08-08 10:41 UTC, olexiy-kireyko commented on src/css/sections/yachts.css
> +  border-radius: 24%;
+

2024-08-08 10:44 UTC, olexiy-kireyko commented on src/css/sections/yachts.css
> +    max-height: 19px;
+

2024-08-08 10:49 UTC, olexiy-kireyko commented on src/css/sections/yachts.css
> +.yachts-list-item {
мені якось треба реалізувати обрізання назви другої яхти (що з'являється з планшетної версії). для реалізації text-overflow: ellipsis; мені треба задати ширину цьому блоку. він і розтягує картку. я інші зауваження усуваю і пропоную запушити, щоб я підключив зображення і погрався вже повністю

2024-08-08 10:53 UTC, olexiy-kireyko commented on src/css/sections/yachts.css
> +  box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.25);
для мобільної версії тінь є, але починаючи з планшета я її не прибрав. усуваю
![image](https://github.com/user-attachments/assets/3ecf1403-5da2-4f7b-8123-d595c8927320)

2024-08-08 11:13 UTC, olexiy-kireyko commented on src/css/sections/yachts.css
> +.yachts-card-line {
done

2024-08-08 11:14 UTC, olexiy-kireyko commented on src/css/sections/yachts.css
> +.yachts-card-testimonial {
done

2024-08-08 11:48 UTC, olexiy-kireyko commented on src/css/sections/yachts.css
> +  opacity: 0.4;
який синтаксис такого запису? те, що нарив в неті, ефекту не дає або треба розділяти змінну кольору на складові r, g, b

2024-08-08 11:48 UTC, olexiy-kireyko commented on src/css/sections/yachts.css
> +.yachts-card-value {
done

2024-08-08 12:12 UTC, olexiy-kireyko commented on src/css/sections/yachts.css
> +.yachts-list-item {
замінив флекс-базис на відс через калк. працює

2024-08-08 13:12 UTC, ratkus-dev commented on src/css/sections/yachts.css
> +  box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.25);
сейчас перетяну макет заново но у меня тени нет

2024-08-08 13:14 UTC, ratkus-dev commented on src/css/sections/yachts.css
> +  box-shadow: 0 4px 4px 0 rgba(0, 0, 0, 0.25);
все равно тени нет и на общем макете
перепроверь у себя

2024-08-09 12:10 UTC, ratkus-dev approved these changes

2024-08-09 12:10 UTC, merged