footer
ratkus-dev/project-DevStudents pull request #12
Opened 2024-08-08 14:21 UTC by Yeromin1

2024-08-08 15:57 UTC, ratkus-dev requested changes

2024-08-08 15:57 UTC, ratkus-dev commented on src/css/sections/footer.css
> +.footer-nav-list {
навигацию переиспользуй с header

2024-08-08 15:57 UTC, ratkus-dev commented on src/partials/footer.html
> +        <p class="footer-text">Privacy Police</p>
это должна быть ссылка

2024-08-08 15:57 UTC, ratkus-dev commented on src/css/sections/footer.css
> +    .footer-logo {
нет стилей для логотипа на мобилке

2024-08-08 15:57 UTC, ratkus-dev commented on src/css/sections/footer.css
> +.footer-logo-nav {
тут добавь align-items: flex-start;

2024-08-08 15:57 UTC, ratkus-dev commented on src/css/sections/footer.css
> +    font-weight: 400;
55 строку можно удалить

2024-08-08 16:54 UTC, Yeromin1 commented on src/css/sections/footer.css
> +.footer-nav-list {
nav-list у тебя есть flex-direction: column; мне он не нужен, нужно обнулить и  все равно нужно будет создавать новый класс. Выигрыша от этого нету, а мне так комфортнее.

2024-08-08 16:54 UTC, Yeromin1 commented on src/partials/footer.html
> +        <p class="footer-text">Privacy Police</p>
Исправил

2024-08-08 16:54 UTC, Yeromin1 commented on src/css/sections/footer.css
> +    .footer-logo {
Исправил

2024-08-08 16:54 UTC, Yeromin1 commented on src/css/sections/footer.css
> +.footer-logo-nav {
Добавил

2024-08-08 16:54 UTC, Yeromin1 commented on src/css/sections/footer.css
> +    font-weight: 400;
font-weight по умолчанию не 400. Нужно оставить

2024-08-09 18:19 UTC, ratkus-dev requested changes

2024-08-09 18:19 UTC, ratkus-dev commented on src/partials/footer.html
> +      <div class="container-footer-text">
измени на footer-text-container

2024-08-09 18:19 UTC, ratkus-dev commented on src/partials/footer.html
> +        <a href="#" class="footer-text">2023. Yacht Adventures</a>
тут не должно быть ссылки тут должен быть или p или span

2024-08-09 18:19 UTC, ratkus-dev commented on src/partials/footer.html
> +      <div class="container-nav-icon">
верхнюю часть footer, а именно разметку нужно переделать как это реализовано в header, то есть у тебя должен быть див в который вложен логотип список ссылок и линки на соц сети, а сейчас у тебя много не нужных оберток

2024-08-09 18:46 UTC, ratkus-dev requested changes

2024-08-09 18:46 UTC, ratkus-dev commented on src/css/sections/footer.css
> +    max-width: 66px;
высоту не нужно задавать используй padding

2024-08-09 18:46 UTC, ratkus-dev commented on src/css/sections/footer.css
> +    background-color: #fbfbfb;
переменная должна быть

2024-08-09 18:46 UTC, ratkus-dev commented on src/css/sections/footer.css
> +    color: #fbfbfb;
аналогично

2024-08-09 18:46 UTC, ratkus-dev commented on src/css/sections/footer.css
> +        gap: 311px;
и таких величин избегай их в целом не должно быть

2024-08-09 18:46 UTC, ratkus-dev commented on src/css/sections/footer.css
> +        gap: 330px;
аналогично

2024-08-09 18:46 UTC, ratkus-dev commented on src/css/sections/footer.css
> +        gap: 388px;
аналогично

2024-08-09 18:46 UTC, ratkus-dev commented on src/css/sections/footer.css
> +        gap: 409px;
аналогично

2024-08-10 08:09 UTC, Yeromin1 commented on src/partials/footer.html
> +      <div class="container-footer-text">
Изменил

2024-08-10 08:10 UTC, Yeromin1 commented on src/partials/footer.html
> +        <a href="#" class="footer-text">2023. Yacht Adventures</a>
Исправил на р

2024-08-10 08:35 UTC, Yeromin1 commented on src/partials/footer.html
> +      <div class="container-nav-icon">
У меня background-color темно-зеленый на всю секцию и есть container с паддингами лево и право по 10рх от header. Как мне их оформить если убрать div? header не такой, у него position: absolute и падинг как у меня ему не нужен.

2024-08-10 08:36 UTC, Yeromin1 commented on src/css/sections/footer.css
> +    max-width: 66px;
это не высота

2024-08-10 08:37 UTC, Yeromin1 commented on src/css/sections/footer.css
> +    background-color: #fbfbfb;
Какая переменная, не пойму?

2024-08-10 08:40 UTC, Yeromin1 commented on src/css/sections/footer.css
> +        gap: 311px;
Это размеры с макета, как их избегать?

2024-08-11 14:26 UTC, ratkus-dev approved these changes

2024-08-11 14:26 UTC, merged